--[[
	Author: Alternator (Massiner of Nathrezim)
	Date:	2014

]]

local AddonName, AddonTable = ...;
local Engine = AddonTable.ButtonEngine;
local C = Engine.Constants;

C.ImagesDir 	= "Interface/Addons/ButtonForgeRebuild/Images/";
C.QUESTION_MARK = "Interface/Icons/INV_Misc_QuestionMark";
C.SUMMON_RANDOM_FAVORITE_MOUNT_SPELL = 150544;
C.SUMMON_RANDOM_FAVORITE_MOUNT_ID = 268435455;
C.PICKUP_SPELL_SOUND = "Sound/Interface/Uspelliconpickup.Wav";
C.DROP_SPELL_SOUND = "Sound/Interface/Uspellicondrop.Wav";
C.MACRO_NOT_FOUND = "MACRO_NOT_FOUND";
C.MACRO_DELETED = "MACRO_DELETED";


C.ERROR_IN_COMBAT_LOCKDOWN = "ERROR_IN_COMBAT_LOCKDOWN";
C.ERROR_BUTTON_NAME_IN_USE = "ERROR_BUTTON_NAME_IN_USE";
C.ERROR_COULD_NOT_IDENTIFY_MOUNT = "ERROR_COULD_NOT_IDENTIFY_MOUNT";
--C.ERROR_COULD_NOT_IDENTIFY_EQUIPMENT_SET = "ERROR_COULD_NOT_IDENTIFY_EQUIPMENT_SET";
C.ERROR_UNRECOGNISED_ACTION = "ERROR_UNRECOGNISED_ACTION";
C.ERROR_REGISTERFORCHANGES_PARAMETERS = "ERROR_REGISTERFORCHANGES_PARAMETERS";
C.ERROR_DEREGISTERFORCHANGES_PARAMETERS = "ERROR_DEREGISTERFORCHANGES_PARAMETERS";
C.ERROR_BUTTON_NOT_FOUND = "ERROR_BUTTON_NOT_FOUND";
C.ERROR_COMMAND_UNSUPPORTED = "ERROR_COMMAND_UNSUPPORTED";
C.ERROR_NOT_BUTTONFORGE_ACTIONBUTTON = "ERROR_NOT_BUTTONFORGE_ACTIONBUTTON";

C.WARNING_EQUIPMENTSET_NAME = "WARNING_EQUIPMENTSET_NAME";

C.INFO_QUEUED_FOR_AFTER_COMBAT = "INFO_QUEUED_FOR_AFTER_COMBAT";


C.EVENT_CURSORCHANGE               = 01;
C.EVENT_SETACTION                  = 02;
C.EVENT_FLYOUTDIRECTION            = 03;
C.EVENT_KEYBINDTEXT                = 04;
C.EVENT_ENABLED                    = 05;
C.EVENT_RESPONDSTOMOUSE            = 06;
C.EVENT_ALPHA                      = 07;
C.EVENT_LOCKED                     = 08;
C.EVENT_ALWAYSSHOWGRID             = 09;
C.EVENT_SHOWTOOLTIP                = 10;
C.EVENT_SHOWKEYBINDTEXT            = 11;
C.EVENT_SHOWCOUNTS                 = 12;
C.EVENT_SHOWMACRONAME              = 13;
C.EVENT_UPDATEACTION               = 14;















