
if not(GetLocale() == "ruRU") then
    return;
end

local L = LibStub("AceLocale-3.0"):NewLocale("GSE", "ruRU")

-- Options translation
L["|cffff0000GS-E:|r Gnome Sequencer - Enhanced Options"] = "|cffff0000GS-E:|r Gnome Sequencer - Расширенные Возможности"
L["Author"] = "Автор"
L["Belt"] = "Пояс"
L["Cancel"] = "Отменить"
L["Clear"] = "Очистить"
L["Clear Errors"] = "Очистить Ошибки"
L["Close"] = "Закрыть"
L["Colour"] = "Цвет"
L["Combat"] = "Бой"
L["Create Icon"] = "Создать иконку"
L["Create Macro"] = "Создать Макрос"
L["Debug"] = "Отладка"
L["Debug Mode Options"] = "Параметры Режима Отладки"
L["Default Version"] = "По Умолчанию"
L["Delete"] = "Удалить"
L["Delete Icon"] = "Удалить иконку"
L["Delete Version"] = "Удалить версию"
L["Disable"] = "Отключить"
L["Display debug messages in Chat Window"] = "Отображение отладочных сообщений в окне чата"
L["Edit"] = "Редактировать"
L["Enable"] = "Включить"
L["Enable Debug for the following Modules"] = "Включить отладку по следующим модулям"
L["Export"] = "Экспорт"
L["Gameplay Options"] = "Игровые Параметры"
L["General"] = "Общие"
L["General Options"] = "Общие Параметры"
L["GSE allows plugins to load Macro Collections as plugins.  You can reload a collection by pressing the button below."] = "GSE allows plugins to load Macro Collections as plugins.  Вы можете перезагрузить коллекцию, нажав на кнопку ниже."
L["Head"] = "Голова"
L["Help URL"] = "URL справка"
L["Icon: "] = "Иконка:"
L["Import"] = "Импорт"
L["KeyPress"] = "Нажатие клавиши"
L["Language"] = "Язык"
L["Neck"] = "Шея"
L["New"] = "Новый"
L["No"] = "Нет"
L["Options"] = "Параметры"
L["Pause"] = "Пауза"
L["Plugins"] = "Плагины"
L["Raid"] = "Рейд"
L["Record"] = "Запись"
L["Record Macro"] = "Запись Макроса"
L["Resets"] = "Сбросы"
L["Resume"] = "Продолжить"
L["Ring 1"] = "Кольцо 1"
L["Ring 2"] = "Кольцо 2"
L["Save"] = "Сохранить"
L["Send"] = "Отправить"
L["Sequence"] = "Последовательность"
L["Sequence Name"] = "Имя Последовательности"
L["Sequence Name: "] = "Имя Последовательности:"
L["Stop"] = "Стоп"
L["Talents"] = "Таланты"
L["Target"] = "Цель"
L["Trinket 1"] = "Аксессуар 1"
L["Trinket 2"] = "Аксессуар 2"
L["Update"] = "Обновить"
L["Use"] = "Использовать"
L["Yes"] = "Да"


